apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smartdocs.fullname" . }}-secrets
  labels:
    {{- include "smartdocs.labels" . | nindent 4 }}
type: Opaque
stringData:
  openai-api-key: {{ .Values.backend.secrets.openaiApiKey | quote }}
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}
  postgres-password: {{ .Values.postgres.auth.password | quote }}
