apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartdocs.fullname" . }}-backend
  labels:
    {{- include "smartdocs.labels" . | nindent 4 }}
    {{- include "smartdocs.backend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smartdocs.backend.selectorLabels" . | nindent 4 }}
